### ISSUE TITLE
show/hide - Funktion SortValue

### ISSUE THREAD

**Issue by Stivino** [SortC/SortC#29]

**Comment by SockeThe2nd** [comment]
WICHTIG:

Gelöst über styleSheet per background: transparent

wichtig ist: ändern der aktion des sortValue setzt das sortValue wieder sichtbar!

wird noch behoben

**Comment by SockeThe2nd** [comment]
bug behoben:

hideValue: setzt valueLabel unsichtbar und valueFrame transparent, layout bleibt erhalten.
                  !!! setAction kann auch auf ein "verstecktes" sortValue aufgerufen werden, die action wird dann gesetzt, das sortValue bleibt jedoch versteckt.

showValue: setzt valueLabel sichtbar, und stellt anhand der aktuellen Action das Styling des valueFrames wieder her.

mehrfaches aufrufen von hideValue bzw showValue hat keinen Effekt.

Aktueller Status des sortValues per getValueVisible()
    return true >>> sortValue sichtbar
    return false >>> sortValue ist versteckt
